export const routes = {
  HOME: '/',
  ABOUTUS: '/about-us',
  NEWPRODUCTS: '/new-products',
  SIGNIN: '/signin',
  SIGNUP: '/signup',
  TRYON: '/try-on',
  RESETPASSWORD: '/reset-password',
  PRODUCT: '/product',
  PROFILE: '/profile',
  ORDERTRACKING: '/manage-order',
  DASHBOARD: '/admin/dashboard',
  MANAGEORDER: '/admin/manage-order',
  MANAGEPRODUCT: '/admin/manage-product',
  DETAILPRODUCT: '/product/:id',
  CART: '/cart',
  CHECKOUT: '/checkout',
  OURCOMMIT: '/our-commit',
  OPERATINGPOLICY: '/operating-policy',
  POLICIESANDREGULATION: '/policies-regulation',
  ORDERINGGUIDE: '/odering-instruction',
  CONTACTGUIDE: '/contact-instruction',
}
